# Generated by Django 6.0.7 on 2026-07-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timer',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
