# Generated by Django 6.0.7 on 2026-07-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_task_order_timer_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='timer',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timer',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
