# Generated by Django 6.0.7 on 2026-07-28 09:58

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_task_options_remove_task_is_done_task_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My LuminoPal', max_length=100)),
                ('device_id', models.CharField(max_length=64, unique=True)),
                ('auth_token', models.CharField(default=secrets.token_hex, editable=False, max_length=128, unique=True)),
                ('pair_code', models.CharField(blank=True, max_length=6)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('wifi_name', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='webapp.task')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lamps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
