# Generated by Django 6.0.7 on 2026-07-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_lamp_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamp',
            name='pair_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
